### ISSUE TITLE
Where is `cargo build-docker-image`?

### ISSUE THREAD

**Issue by memark** [cross-rs/cross-toolchains#36]
In several of the examples, commands beginning with `cargo build-docker-image` are run. Where can this cargo tool `build-docker-image` be found? I've googled up a couple of close-named relatives, but not this specific one.

**Comment by Emilgardis** [comment]
It's defined here!

`https://github.com/cross-rs/cross/blob/6982b6c8f97b9db56bc6e005427d2367bb39a93f/.cargo/config.toml#L3`

which is https://github.com/cross-rs/cross/blob/6982b6c8f97b9db56bc6e005427d2367bb39a93f/xtask/src/build_docker_image.rs#L100

So, cross-toolchains need to be used as a submodule in the [cross repo](https://github.com/cross-rs/cross), and then with `cargo build-docker-image` you can invoke the alias

**Comment by memark** [comment]
Great, thanks! @Emilgardis
