### ISSUE TITLE
Can't configure crosstool for x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by amosjyng** [cross-rs/cross-toolchains#41]
Hey, I'm trying to build an image to support a `x86_64-unknown-linux-gnu` target with version 2.25 for glibc, instead of the current version 2.23 used on `ghcr.io/cross-rs/x86_64-unknown-linux-gnu`. But it seems I am unable to configure it:

```
$ GLIBC_VERSION=2.25 cargo xtask configure-crosstool x86_64-unknown-linux-gnu
...
     Running `target/debug/xtask configure-crosstool x86_64-unknown-linux-gnu`
Error: 
   0: unable to find config for target "x86_64-unknown-linux-gnu"

Location:
   xtask/src/crosstool.rs:73

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

It doesn't work with `x86_64-unknown-linux-gnu-sde-cross` either. Am I misunderstanding something?

Thanks!

**Comment by amosjyng** [comment]
Ah I see, I guess I have to build my own Docker image based on a Ubuntu release that has the glibc version I want. Let me know if there's a better way to target `x86_64-unknown-linux-gnu`

**Comment by Emilgardis** [comment]
You could use crosstool-ng, just need to add it as a target for configure-crosstool

You could use https://github.com/cross-rs/cross/wiki/Configuration#targettargetzig

**Comment by amosjyng** [comment]
Ah got it, thank you!
